name: MooseCI

on: pull_request

permissions:
  contents: read
  actions: write
  pull-requests: write

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: moosetechnology/setup-MooseCI@v1
        with:
          project-path: ./app/src/main/java/fr
          project-language: java
